### ISSUE TITLE
Add additional residential communities for $home options

### ISSUE THREAD

**Issue by GavHern** [cabalex/slugschedule#5]
## Summary
I noticed some of the on-campus housing communities which are not college-affiliated were missing, which would be a nice small feature. I was going to make a pull request but it seemed as simple as adding to the select menu so I figured an issue is more appropriate. Let me know you'd prefer a PR!

## Communities
- The Village
- Graduate Student Housing/Redwood Grove
- Family Student Housing
- Camper Park

## Quirks
- Although UCSC calls the communities "Redwood Grove" and "Camper Park", Google Maps will refer those to other locations in Santa Cruz. To fix this, they should be "Redwood Grove Apartments" and "UCSC Trailer Park".
- Graduate Student Housing and Redwood Grove are connected and practically are the same community, so maybe it's redundant to have both... Practically speaking, it does make a difference for walking so I feel like they're best as separate options.
- The Village isn't really walkably connected to campus so it may not be worthwhile to have on here, but it's probably best for consistency. Similarly, University Town Center isn't connected to campus but should be covered by the "Off Campus" option.
- Potential future updates may be needed if UCSC decides to discontinue the Camper Park as they've suggested, as well as when Family Student Housing is moved to lower campus in the coming few years and the construction of the Student Housing West project in ~2025.

## Proposed Markup
```svelte
<option>The Village</option>
<option value="Redwood Grove Apartments">Redwood Grove</option>
<option>Graduate Student Housing</option>
<option>Family Student Housing</option>
<option value="UCSC Trailer Park">Camper Park</option>
```

I really appreciate this tool! It's one of those ideas that had crossed my mind and I'm glad to see someone beat me to it!

**Comment by cabalex** [comment]
I've just added these in the newest commit, so they should be reflected on the site soon.

Thank you for submitting such a professional request! Glad you're enjoying it.

**Comment by GavHern** [comment]
Ah wait it didn't even hit me that this is more of a relaxed project so I didn't have to be so extra with the issue haha

**Comment by cabalex** [comment]
I appreciate the extraness!! If you're curious why it only took me 5 minutes to merge, that's why 😊
